/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pTDMo3Pi7bA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";

export function Frequently() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="space-y-4 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Frequently Asked Questions</h2>
          <p
            className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Get answers to the most common questions about our product.
          </p>
        </div>
        <div className="mt-12 rounded-lg border">
          <Accordion type="single" collapsible>
            <AccordionItem value="item-1">
              <AccordionTrigger className="flex items-center justify-between gap-4 px-6 py-4 text-left">
                <h3 className="text-lg font-medium">What is the difference between the Basic and Pro plans?</h3>
                <div className="h-5 w-5 text-muted-foreground" />
              </AccordionTrigger>
              <AccordionContent className="border-t px-6 py-4">
                <div className="space-y-2 text-muted-foreground">
                  <p>
                    The Basic plan includes essential features for small teams, while the Pro plan offers advanced
                    functionality and increased limits for larger organizations.
                  </p>
                  <p>Key differences include: team size, storage, custom branding, and priority support.</p>
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-2">
              <AccordionTrigger className="flex items-center justify-between gap-4 px-6 py-4 text-left">
                <h3 className="text-lg font-medium">How do I cancel my subscription?</h3>
                <div className="h-5 w-5 text-muted-foreground" />
              </AccordionTrigger>
              <AccordionContent className="border-t px-6 py-4">
                <div className="space-y-2 text-muted-foreground">
                  <p>
                    To cancel your subscription, log into your account and navigate to the Billing section. There you
                    will find an option to cancel your plan.
                  </p>
                  <p>
                    Please note that we do not offer refunds for partial billing periods. Your subscription will remain
                    active until the end of the current billing cycle.
                  </p>
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-3">
              <AccordionTrigger className="flex items-center justify-between gap-4 px-6 py-4 text-left">
                <h3 className="text-lg font-medium">What payment methods do you accept?</h3>
                <div className="h-5 w-5 text-muted-foreground" />
              </AccordionTrigger>
              <AccordionContent className="border-t px-6 py-4">
                <div className="space-y-2 text-muted-foreground">
                  <p>
                    We accept all major credit cards, including Visa, Mastercard, American Express, and Discover. We
                    also accept PayPal and Apple Pay.
                  </p>
                  <p>
                    Payments are processed securely, and we do not store any sensitive financial information on our
                    servers.
                  </p>
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-4">
              <AccordionTrigger className="flex items-center justify-between gap-4 px-6 py-4 text-left">
                <h3 className="text-lg font-medium">Do you offer any discounts or promotions?</h3>
                <div className="h-5 w-5 text-muted-foreground" />
              </AccordionTrigger>
              <AccordionContent className="border-t px-6 py-4">
                <div className="space-y-2 text-muted-foreground">
                  <p>Yes, we offer several discounts and promotions throughout the year. These include:</p>
                  <ul className="list-disc space-y-1 pl-4">
                    <li>Annual billing discounts</li>
                    <li>Referral programs</li>
                    <li>Holiday and seasonal promotions</li>
                    <li>Discounts for non-profit organizations</li>
                  </ul>
                  <p>Be sure to check our website or contact our sales team for the latest offers.</p>
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-5">
              <AccordionTrigger className="flex items-center justify-between gap-4 px-6 py-4 text-left">
                <h3 className="text-lg font-medium">How long does it take to get started?</h3>
                <div className="h-5 w-5 text-muted-foreground" />
              </AccordionTrigger>
              <AccordionContent className="border-t px-6 py-4">
                <div className="space-y-2 text-muted-foreground">
                  <p>
                    Getting started with our platform is quick and easy. After signing up, you can be up and running in
                    just a few minutes.
                  </p>
                  <p>
                    Our intuitive onboarding process will guide you through setting up your account, connecting your
                    data sources, and customizing your dashboard. Our support team is also available to assist you every
                    step of the way.
                  </p>
                </div>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
      </div>
    </section>)
  );
}
